// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iljkckqqahcutzsukzkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsamtja3FxYWhjdXR6c3VremtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDAxMTMsImV4cCI6MjA3MTI3NjExM30.AweX-33vRNqrgLMGY37-Vn8edz2JIYFh19oeCOEuwAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});